### ISSUE TITLE
Can we please rename this repository to Windsor.Quartz?

### ISSUE THREAD

**Issue by fir3pho3nixx** [castleproject/Windsor.Quartz#30]
I am just having trouble with the aesthetic naming of this project when viewed in github. 

The good bit. 

![image](https://user-images.githubusercontent.com/607402/44235364-26f1fd80-a1a1-11e8-912f-7a925aa71790.png)

The ugly bit. 

![image](https://user-images.githubusercontent.com/607402/44235396-41c47200-a1a1-11e8-8375-e7dae69a908d.png)

Can we please conventionalise our repository naming standards? Let's make it pretty again 🦄

**Comment by jonorossi** [comment]
I don't really have an objection other than the .NET ecosystem has slowly moved to using package names to describe projects, it is a little annoying that people use "Castle.Core" (with the dot) to describe something in DynamicProxy but that is the way it is as that is how we ship it. This rename might confuse people to think "Windsor.Quartz" is the package name, what about "Windsor-Quartz"?

With that said I've noticed when people fork the "Core" repo they then by default get a repo named "Core" in their user, doesn't quite make a lot of sense, but I didn't really want longer URLs and repos have more than one package anyway.

@kristofdc @stakx did you have any preference?

P.S. I've renamed `castleproject.github.io` to `castleproject.org` since GitHub no longer requires a repo to be named a certain away, there are settings for GitHub Pages now.

**Comment by stakx** [comment]
@jonorossi - I might be missing some background information here, but why does Castle.Facilities.Quartz even get its own repository when all the other Windsor facilities are directly contained in the Windsor repository? If we merged Castle.Facilities.Quartz into Windsor, the naming issue raised here would simply evaporate, as this repo already follows [the naming pattern used over at Windsor ("Castle.Facilities.*")](https://github.com/castleproject/Windsor/tree/master/src).

Other than that, I have no clear preference. A few stray thoughts for consideration:

* I'm not a great fan of having long, repetitive repository names. I like short names. I don't think we need a "Castle." prefix in every repository's name, since our organization already contains that term. Ideally, our GitHub organization would be called simply "castle" instead of "castleproject" (but it's perhaps too late for that), that way it would be super easy to guess the right NuGet package names, e.g. "Castle.Windsor" for "castle/Windsor" etc.

* I don't think we're obligated to worry extensively about the names of forks. Let the forkers deal with that. If they don't want their fork of Castle.Core to be called just "Core" (which indeed isn't a very telling name), they can always rename their fork ([like I did](https://github.com/stakx/Castle.Core)). In other words, this shouldn't be a reason for us to prefix every repo name with "Castle.".

* If you followed the above suggestions, and Castle.Facilities.Quartz stayed a separate repository, you'd probably have to rename it to "Facilities.Quartz", which is rather horrible. But I think that is more a consequence of facilities being named "Castle.Facilities.\*" when they really should be named "Castle.Windsor.Facilities.*", since they're apparently specific to Windsor. But I understand that it's perhaps too late to rename them all.

**Comment by jonorossi** [comment]
> why does Castle.Facilities.Quartz even get its own repository when all the other Windsor facilities are directly contained in the Windsor repository?

The Quartz facility was never part of any Windsor distribution, it was a contrib project that was always outside of Windsor just as there were heaps of other facilities for integration with Windows Fax Services, message queues and all sorts of things. It just happens that this one made its way from an old subversion repo into git and on our GitHub.

> If we merged Castle.Facilities.Quartz into Windsor, the naming issue raised here would simply evaporate

In a Windsor issue (https://github.com/castleproject/Windsor/issues/339) we've actually been talking about the future of those facilities over the last 12 months, some have been deprecated and got moved to [the deprecated org](https://github.com/castleproject-deprecated/Castle.Windsor.Facilities/tree/master/src) so that people can get at the source code easily but aren't shipped with Windsor anymore. We now only have 2 facilities left with the main Windsor distribution outside of `Castle.Windsor.dll`, Logging and WCF. We've discussed rewriting the logging facility to something completely different, heaps smaller and with no external dependencies (which is why we didn't merge it in), and the WCF facility is likely to be moved out in the future.

> IMO, consistent names are more important than any one particular repo name, so in that regard I welcome @fir3pho3nixx raising the naming topic.

Agreed. Thanks for your comments, they align with where I was coming from when I renamed this repo a few months ago, we already had Castle.Transactions from many years ago but I didn't really like the name.

So I guess that brings us to:
- Windsor.Quartz, or
- Windsor-Quartz

And we rename "Castle.Transactions" to just "Transactions".

**Comment by fir3pho3nixx** [comment]
I am a fan of the `.`, the `-` not so much.

**Comment by jonorossi** [comment]
> I am a fan of the ., the - not so much.

Thanks for weighing in, I wasn't really strong either way so let's go with the dot and be done with it. No one else expressed any concerns.

I've renamed both this and Castle.Transactions.

**Comment by fir3pho3nixx** [comment]
Looks great :)
